/**
 * Single place where message content becomes HTML.
 *
 * Message and tool content is not trusted: it can come from an LLM, from a web
 * page fetched by a skill, or from a database row written by a third party.
 * Rendering it with markdown-it in `html: true` mode (which we want to keep,
 * because HTML in tool output is useful) emits that content verbatim, so it is
 * post-processed with sanitize-html. That has two effects:
 *
 *  - scripts, event handlers, styles and javascript: URLs are removed
 *  - the fragment is re-parsed and re-serialized, so unclosed tags are closed
 *    and structural markup can no longer leak out of the message bubble
 */
const MarkdownIt = require("markdown-it");
const sanitizeHtml = require("sanitize-html");

const md = new MarkdownIt({ html: true, breaks: true, linkify: true });

const allowedTags = [
  ...sanitizeHtml.defaults.allowedTags,
  "img",
  "details",
  "summary",
  "ins",
  "del",
];

const sanitizeOpts = {
  allowedTags,
  allowedAttributes: {
    a: ["href", "name", "target", "title", "rel", "download"],
    img: ["src", "srcset", "alt", "title", "width", "height", "loading"],
    td: ["colspan", "rowspan", "align"],
    th: ["colspan", "rowspan", "align", "scope"],
    ol: ["start", "type"],
    li: ["value"],
    details: ["open"],
    // classes are needed for code highlighting and for our own markup.
    // deliberately not allowed: style (layout breakage, e.g. position: fixed),
    // id (collides with the ids the chat view addresses), on* handlers
    "*": ["class"],
  },
  allowedSchemes: ["http", "https", "mailto", "tel", "ftp"],
  allowedSchemesByTag: {
    img: ["http", "https", "data"],
  },
  // script/style contents are dropped rather than emitted as text
  disallowedTagsMode: "discard",
  transformTags: {
    a: sanitizeHtml.simpleTransform("a", {
      target: "_blank",
      rel: "noopener noreferrer",
    }),
  },
};

const toStr = (s) => (typeof s === "string" ? s : s == null ? "" : String(s));

// Markdown (possibly containing inline HTML) -> safe HTML
const renderMd = (s) => sanitizeHtml(md.render(toStr(s)), sanitizeOpts);

// Already-rendered chat markup -> the same markup, structurally closed off.
// The fragment is re-parsed and re-serialized, so an element left unclosed by
// whatever produced it (a tool response truncated in the middle of a tag, for
// instance) is closed here instead of swallowing everything that follows it on
// the page. Nothing is removed: tags, attributes and event handlers are all
// kept, because this also runs over markup saltcorn itself generated - views
// embedded by a skill, user action buttons - which relies on them. It is
// containment, not sanitization: use renderMd or sanitizeFragment for content
// that has not been through them yet.
const balanceHtml = (h) =>
  sanitizeHtml(toStr(h), {
    allowedTags: false,
    allowedAttributes: false,
    // deliberately keeps what it is given, script and style included: this is
    // not the pass that decides what is safe
    allowVulnerableTags: true,
  });

// Raw HTML fragment from an untrusted source -> safe HTML.
// Do not use this on markup generated by saltcorn itself (view.run() output,
// action buttons): that is trusted and relies on ids, styles and handlers.
const sanitizeFragment = (h) => sanitizeHtml(toStr(h), sanitizeOpts);

module.exports = { renderMd, sanitizeFragment, balanceHtml, md, sanitizeOpts };
